export default {
  subagents: 'Subagents',
  checkpointing: 'Checkpointing',
  rewind: 'Rewind',
  'mcp-diagnostics': 'MCP Diagnostics',
  'policy-explain-mode': 'Policy Explain Mode',
  'release-channels': 'Release Channels',
  'server-openapi-contracts': 'Server OpenAPI Contracts',
  'eval-suite-expansion': 'Eval Suite Expansion',
  'performance-budgets': 'Performance Budgets',
  'session-workflows': 'Session Workflows',
  'github-automation': 'GitHub Automation',
  sandbox: 'Sandbox Support',
  headless: 'Headless Mode',
  'welcome-back': 'Welcome Back',
  'token-caching': 'Token Caching',
  'admin-controls-site': 'Admin Control Site',
  'safety-admin-core-cli': 'Safety, Admin Controls, and Core/CLI Enhancements',
};
