export default {
  index: 'Introduction',
  authentication: 'Authentication',
  'openai-auth': 'OpenAI Authentication',
  commands: 'Commands',
  'sdk-typescript': 'TypeScript SDK',
  'sdk-typescript-multi-agent-skills': 'TypeScript SDK Multi-agent & Skills',
  'sdk-python': 'Python SDK',
  'sdk-python-multi-agent-skills': 'Python SDK Multi-agent & Skills',
  scheduler: 'Scheduler',
  configuration: 'Configuration',
  'configuration-v1': 'Configuration (v1)',
  'remote-driving': 'Remote Driving',
  themes: 'Themes',
  tutorials: 'Tutorials',
  'keyboard-shortcuts': 'Keyboard Shortcuts',
  'trusted-folders': 'Trusted Folders',
  'papert-ignore': 'Ignoring Files',
  Uninstall: 'Uninstall',
};
