/**
 * @license
 * Copyright 2026 Papert-code
 * SPDX-License-Identifier: Apache-2.0
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  REMOTE_CONTROL_OPENAPI_CONTRACT_ID,
  REMOTE_CONTROL_OPENAPI_CONTRACT_VERSION,
  REMOTE_CONTROL_OPENAPI_SPEC,
} from '../packages/a2a-server/src/http/openapi.js';

const REQUIRED_OPERATION_IDS = new Set([
  'remoteHealth',
  'createRemoteSession',
  'releaseRemoteSession',
  'getWebUiCatalog',
  'updateWebUiReleaseChannel',
]);

function assertSpecHasRequiredOperationIds(): void {
  const foundOperationIds = new Set<string>();
  for (const pathItem of Object.values(REMOTE_CONTROL_OPENAPI_SPEC.paths)) {
    for (const operation of Object.values(pathItem)) {
      if (operation.operationId) {
        foundOperationIds.add(operation.operationId);
      }
    }
  }
  for (const operationId of REQUIRED_OPERATION_IDS) {
    if (!foundOperationIds.has(operationId)) {
      throw new Error(
        `OpenAPI contract is missing required operationId "${operationId}".`,
      );
    }
  }
}

function generateTypeScriptClient(): string {
  const version = REMOTE_CONTROL_OPENAPI_CONTRACT_VERSION;
  const contractId = REMOTE_CONTROL_OPENAPI_CONTRACT_ID;
  return `/**
 * @license
 * Copyright 2026 Papert-code
 * SPDX-License-Identifier: Apache-2.0
 */

/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/generate-remote-api-clients.ts from packages/a2a-server/src/http/openapi.ts

export const REMOTE_CONTROL_OPENAPI_CONTRACT_VERSION = '${version}' as const;
export const REMOTE_CONTROL_OPENAPI_CONTRACT_ID = '${contractId}' as const;

export type ReleaseChannel = 'stable' | 'preview' | 'nightly';

export interface ErrorResponse {
  error: string;
  code?: string;
}

export interface HealthResponse {
  status: string;
}

export interface CreateRemoteSessionResponse {
  sessionId: string;
  token: string;
  expiresAtMs: number;
  workspaceRoot: string;
}

export interface ReleaseRemoteSessionParams {
  sessionId: string;
  sessionToken: string;
}

export interface WebUiCatalogResponse {
  tools?: unknown[];
  agents?: unknown[];
  skills?: unknown[];
  mcps?: unknown[];
  schedules?: unknown[];
  rewindPoints?: unknown[];
  releaseChannel?: ReleaseChannel;
  releaseChannelGate?: {
    current?: ReleaseChannel;
    nextPromotionTarget?: ReleaseChannel | null;
    readyForPromotion?: boolean;
    requiredSoakMs?: number;
    soakElapsedMs?: number;
    soakRemainingMs?: number;
  };
  [key: string]: unknown;
}

export interface WebUiSessionParams {
  sessionId: string;
  sessionToken: string;
}

export interface UpdateWebUiReleaseChannelParams extends WebUiSessionParams {
  releaseChannel: ReleaseChannel;
}

type FetchLike = (input: URL | string, init?: RequestInit) => Promise<Response>;

export interface RemoteControlApiClientOptions {
  baseUrl: string;
  fetchImpl?: FetchLike;
}

export class RemoteControlApiError extends Error {
  readonly status: number;
  readonly statusText: string;
  readonly body?: unknown;

  constructor(
    message: string,
    details: { status: number; statusText: string; body?: unknown },
  ) {
    super(message);
    this.name = 'RemoteControlApiError';
    this.status = details.status;
    this.statusText = details.statusText;
    this.body = details.body;
  }
}

export class RemoteControlApiClient {
  private readonly baseUrl: string;
  private readonly fetchImpl: FetchLike;

  constructor(options: RemoteControlApiClientOptions) {
    this.baseUrl = options.baseUrl;
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  async remoteHealth(): Promise<HealthResponse> {
    return this.requestJson<HealthResponse>('/api/v1/health', { method: 'GET' });
  }

  async createRemoteSession(
    serverToken?: string,
  ): Promise<CreateRemoteSessionResponse> {
    const headers: Record<string, string> = {};
    if (serverToken && serverToken.trim().length > 0) {
      headers.authorization = \`Bearer \${serverToken}\`;
    }
    return this.requestJson<CreateRemoteSessionResponse>('/api/v1/sessions', {
      method: 'POST',
      headers,
    });
  }

  async releaseRemoteSession(params: ReleaseRemoteSessionParams): Promise<void> {
    await this.requestNoContent(
      \`/api/v1/sessions/\${encodeURIComponent(params.sessionId)}/release\`,
      {
        method: 'POST',
        headers: {
          authorization: \`Bearer \${params.sessionToken}\`,
        },
      },
    );
  }

  async getWebUiCatalog(params: WebUiSessionParams): Promise<WebUiCatalogResponse> {
    return this.requestJson<WebUiCatalogResponse>('/api/v1/webui/catalog', {
      method: 'GET',
      headers: {
        authorization: \`Bearer \${params.sessionToken}\`,
        'x-papert-session-id': params.sessionId,
      },
    });
  }

  async updateWebUiReleaseChannel(
    params: UpdateWebUiReleaseChannelParams,
  ): Promise<void> {
    await this.requestNoContent('/api/v1/webui/release-channel', {
      method: 'PUT',
      headers: {
        authorization: \`Bearer \${params.sessionToken}\`,
        'x-papert-session-id': params.sessionId,
        'content-type': 'application/json',
      },
      body: JSON.stringify({ releaseChannel: params.releaseChannel }),
    });
  }

  private async requestJson<T>(pathName: string, init: RequestInit): Promise<T> {
    const res = await this.fetchImpl(new URL(pathName, this.baseUrl), init);
    const body = await this.readBody(res);
    if (!res.ok) {
      throw new RemoteControlApiError(
        \`Remote API request failed: \${res.status} \${res.statusText}\`,
        { status: res.status, statusText: res.statusText, body },
      );
    }
    return body as T;
  }

  private async requestNoContent(pathName: string, init: RequestInit): Promise<void> {
    const res = await this.fetchImpl(new URL(pathName, this.baseUrl), init);
    if (res.status === 204) {
      return;
    }
    const body = await this.readBody(res);
    if (!res.ok) {
      throw new RemoteControlApiError(
        \`Remote API request failed: \${res.status} \${res.statusText}\`,
        { status: res.status, statusText: res.statusText, body },
      );
    }
  }

  private async readBody(res: Response): Promise<unknown> {
    const contentType = res.headers.get('content-type') ?? '';
    if (contentType.includes('application/json')) {
      return await res.json();
    }
    const text = await res.text();
    if (!text) {
      return undefined;
    }
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  }
}
`;
}

function generatePythonClient(): string {
  const version = REMOTE_CONTROL_OPENAPI_CONTRACT_VERSION;
  const contractId = REMOTE_CONTROL_OPENAPI_CONTRACT_ID;
  return `"""
@license
Copyright 2026 Papert-code
SPDX-License-Identifier: Apache-2.0
"""

# AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
# Generated by scripts/generate-remote-api-clients.ts from packages/a2a-server/src/http/openapi.ts

from __future__ import annotations

import json
from typing import Any, Callable, Dict, Mapping, Optional, Tuple, TypedDict
from urllib.error import HTTPError
from urllib.request import Request, urlopen

REMOTE_CONTROL_OPENAPI_CONTRACT_VERSION = "${version}"
REMOTE_CONTROL_OPENAPI_CONTRACT_ID = "${contractId}"

ReleaseChannel = str


class ErrorResponse(TypedDict, total=False):
    error: str
    code: str


class HealthResponse(TypedDict):
    status: str


class CreateRemoteSessionResponse(TypedDict):
    sessionId: str
    token: str
    expiresAtMs: float
    workspaceRoot: str


class WebUiCatalogResponse(TypedDict, total=False):
    tools: list
    agents: list
    skills: list
    mcps: list
    schedules: list
    rewindPoints: list
    releaseChannel: ReleaseChannel
    releaseChannelGate: Dict[str, Any]


HttpResponse = Tuple[int, Mapping[str, str], bytes]
RequestImpl = Callable[[str, str, Dict[str, str], Optional[bytes]], HttpResponse]


class RemoteControlApiError(Exception):
    def __init__(self, message: str, status: int, status_text: str, body: Any = None):
        super().__init__(message)
        self.status = status
        self.status_text = status_text
        self.body = body


class RemoteControlApiClient:
    def __init__(
        self,
        base_url: str,
        request_impl: Optional[RequestImpl] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        self._request_impl = request_impl or _default_request_impl

    def remote_health(self) -> HealthResponse:
        body = self._request_json("GET", "/api/v1/health")
        return body

    def create_remote_session(
        self,
        server_token: Optional[str] = None,
    ) -> CreateRemoteSessionResponse:
        headers: Dict[str, str] = {}
        if server_token and server_token.strip():
            headers["authorization"] = f"Bearer {server_token}"
        body = self._request_json("POST", "/api/v1/sessions", headers=headers)
        return body

    def release_remote_session(self, session_id: str, session_token: str) -> None:
        self._request_no_content(
            "POST",
            f"/api/v1/sessions/{session_id}/release",
            headers={"authorization": f"Bearer {session_token}"},
        )

    def get_webui_catalog(self, session_id: str, session_token: str) -> WebUiCatalogResponse:
        body = self._request_json(
            "GET",
            "/api/v1/webui/catalog",
            headers={
                "authorization": f"Bearer {session_token}",
                "x-papert-session-id": session_id,
            },
        )
        return body

    def update_webui_release_channel(
        self,
        session_id: str,
        session_token: str,
        release_channel: ReleaseChannel,
    ) -> None:
        payload = json.dumps({"releaseChannel": release_channel}).encode("utf-8")
        self._request_no_content(
            "PUT",
            "/api/v1/webui/release-channel",
            headers={
                "authorization": f"Bearer {session_token}",
                "x-papert-session-id": session_id,
                "content-type": "application/json",
            },
            body=payload,
        )

    def _request_json(
        self,
        method: str,
        path: str,
        headers: Optional[Dict[str, str]] = None,
        body: Optional[bytes] = None,
    ) -> Any:
        url = f"{self._base_url}{path}"
        status, response_headers, response_body = self._request_impl(
            method,
            url,
            headers or {},
            body,
        )
        parsed = _decode_body(response_headers, response_body)
        if status < 200 or status >= 300:
            raise RemoteControlApiError(
                f"Remote API request failed: {status}",
                status,
                str(status),
                parsed,
            )
        return parsed

    def _request_no_content(
        self,
        method: str,
        path: str,
        headers: Optional[Dict[str, str]] = None,
        body: Optional[bytes] = None,
    ) -> None:
        url = f"{self._base_url}{path}"
        status, response_headers, response_body = self._request_impl(
            method,
            url,
            headers or {},
            body,
        )
        if status == 204:
            return
        parsed = _decode_body(response_headers, response_body)
        if status < 200 or status >= 300:
            raise RemoteControlApiError(
                f"Remote API request failed: {status}",
                status,
                str(status),
                parsed,
            )


def _decode_body(headers: Mapping[str, str], body: bytes) -> Any:
    if not body:
        return None
    content_type = headers.get("content-type", "")
    text = body.decode("utf-8", errors="replace")
    if "application/json" in content_type.lower():
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return text
    return text


def _default_request_impl(
    method: str,
    url: str,
    headers: Dict[str, str],
    body: Optional[bytes],
) -> HttpResponse:
    request = Request(url, data=body, method=method)
    for key, value in headers.items():
        request.add_header(key, value)

    try:
        with urlopen(request) as response:
            status = int(response.status)
            response_headers = {key.lower(): value for key, value in response.headers.items()}
            response_body = response.read()
            return status, response_headers, response_body
    except HTTPError as error:
        error_body = error.read() if hasattr(error, "read") else b""
        response_headers = {key.lower(): value for key, value in error.headers.items()}
        return int(error.code), response_headers, error_body
`;
}

async function writeIfChanged(filePath: string, contents: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  let previous = '';
  try {
    previous = await readFile(filePath, 'utf8');
  } catch {
    // File doesn't exist yet.
  }
  if (previous !== contents) {
    await writeFile(filePath, contents, 'utf8');
  }
}

async function main(): Promise<void> {
  assertSpecHasRequiredOperationIds();

  const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

  const tsClientPath = path.join(
    rootDir,
    'packages/sdk-typescript/src/generated/remoteControlApiClient.ts',
  );
  const pyClientPath = path.join(
    rootDir,
    'packages/sdk-python/src/papert_code_sdk/generated/remote_control_api_client.py',
  );
  const pyInitPath = path.join(
    rootDir,
    'packages/sdk-python/src/papert_code_sdk/generated/__init__.py',
  );

  await writeIfChanged(tsClientPath, generateTypeScriptClient());
  await writeIfChanged(pyClientPath, generatePythonClient());
  await writeIfChanged(
    pyInitPath,
    [
      'from .remote_control_api_client import (',
      '    REMOTE_CONTROL_OPENAPI_CONTRACT_VERSION,',
      '    REMOTE_CONTROL_OPENAPI_CONTRACT_ID,',
      '    RemoteControlApiClient,',
      '    RemoteControlApiError,',
      ')',
      '',
      '__all__ = [',
      '    "REMOTE_CONTROL_OPENAPI_CONTRACT_VERSION",',
      '    "REMOTE_CONTROL_OPENAPI_CONTRACT_ID",',
      '    "RemoteControlApiClient",',
      '    "RemoteControlApiError",',
      ']',
      '',
    ].join('\n'),
  );

  console.log(
    `[generate-remote-api-clients] generated SDK clients for contract ${REMOTE_CONTROL_OPENAPI_CONTRACT_ID}@${REMOTE_CONTROL_OPENAPI_CONTRACT_VERSION}`,
  );
}

await main();
